# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ark',
            old_name='url',
            new_name='target',
        ),
    ]
